## 1. define the depth
MKPATH = ../

## 2. add the parent directories of ANY projects that have header files (hdr) that *this* leaf project needs.
INCDIRS = . startup vorago/drivers/hal vorago/mcu vorago/BSP/evk vorago/utils

## 3. now, calculate the definitions...
include $(MKPATH)/component.mk

